### DISCUSSION TITLE
Proposal: Native Rule Suppression Mechanism in OpenAPI

### DISCUSSION THREAD

**Discussion by apiarya** [OAI/sig-moonwalk#172] [Ideas]
## Rationale  
OpenAPI Specifications are commonly validated using linters, validators, or doctors to enforce best practices. These tools apply both standard and custom rules that evolve over time, introducing more refined checks. However, enforcing all rules strictly is not always practical—some violations are unavoidable due to legacy constraints or business requirements.  

Current suppression mechanisms are too broad, often requiring disabling a rule entirely or ignoring an entire OpenAPI file—neither of which is feasible for APIs with operations distributed across multiple locations. A more **granular approach** is needed to **suppress specific issues on a case-by-case basis** while maintaining overall rule enforcement. Instead of fully suppressing a rule, a better alternative is to **downgrade its severity**, preventing it from negatively impacting the overall API score.  

At present, inline rule suppression is handled using vendor extensions such as `x-suppress-issues`. This proposal advocates for **formalizing rule suppression as an official notation in OpenAPI**, providing a standardized mechanism to acknowledge and manage rule exceptions across tooling and implementations. Linters can recognize suppressions and take actions accordingly in their rule engine.

## Proposed Solution  
A structured mechanism like the following could be used to record and manage rule exceptions. In this example, the `delete` operation violates the rule [`no-http-verbs-in-path`](https://redocly.com/docs/cli/rules/oas/no-http-verbs-in-paths), but the issue cannot be resolved due to legacy constraints.  

```yaml
/bookings/{bookingId}/delete:
    suppress-issues:
      - ruleId: no-http-verbs-in-path
        reason: |
          This is a legacy operation that cannot be removed in this KTLO product line.
          Fixing this issue would be a breaking change.
          Exception #gov6145 approved by joe@example.com on Feb 16, 2023.
        override-severity: info   
    parameters:
      - name: bookingId
        in: path
        ...
    delete:
      summary: Delete a booking
    ...
```

This approach ensures API quality without penalizing entire specifications for necessary legacy design choices. It provides a transparent, structured way to manage exceptions while maintaining governance, compliance, and alignment with evolving API standards.

## Structure  
The structure itself is open for discussion, but we propose starting with the following:
- **`suppress-issues`** – An array of rule suppressions. Multiple rules can be listed, each with its own justification.  
- **`ruleId`** – The unique identifier of the rule to suppress. Optionally, `*` could be supported to suppress all rules for a specific case.  
- **`reason`** – A detailed justification for the suppression, including **why** it is necessary. This can also capture organization-specific details such as **who approved it, when, and under what circumstances**.  
- **`override-severity`** – If omitted, the issue is fully suppressed. When provided, it **downgrades** the severity instead of removing the issue, allowing it to be **captured, recorded, and tracked externally**.  

## References
* https://github.com/zalando/zally/issues/406
* [Turning Sonar off for certain code](https://stackoverflow.com/questions/10971968/turning-sonar-off-for-certain-code)
