### DISCUSSION TITLE
Can we simplify paths further?

### DISCUSSION THREAD

**Discussion by jugaadi** [OAI/sig-moonwalk#23] [Ideas]
Can we simplify paths with the help of nested paths especially now that paths can be referenced? 

PS: This is under the assumption that majority of API users follow the below pattern:
| Operation                      | Method        | Path           |
| ---------------------- | ------------ | ----------- |
| Create a resource Foo | POST            | `/foo`        |
| Fetch Foo collection    | GET               | `/foo`        |
| Update Foo object       | PUT/PATCH  | `/foo/{id}` |
| Fetch Foo object          | GET               | `/foo/{id}` |
| Delete Foo object         | DELETE        | `/foo/{id}` |

```yaml
foo:
    # primary path
    post:
    get:
    paths:
        '{id}':
            # resource object
           patch:
           delete:
           get:
           paths:
               bar:
               # related resource, etc
```
