### DISCUSSION TITLE
Template paths in security schemas

### DISCUSSION THREAD

**Discussion by pavelkornev** [OAI/sig-moonwalk#50] [Ideas]
There is a long standing issue — https://github.com/OAI/OpenAPI-Specification/issues/551 (duplicates: https://github.com/OAI/OpenAPI-Specification/issues/1339, https://github.com/OAI/OpenAPI-Specification/issues/2322)

99% of APIs at SAP, which use OAS to document APIs, have to parametrize security URLs like `tokenUrl` or `authorizationUrl`. According the the issue above, we are not a single organization who would benefit of this.

The [original proposal](https://github.com/OAI/OpenAPI-Specification/issues/551#issuecomment-564932302) from the community would work seamlessly for us and seems to be reasonable:
```yaml
  securitySchemes:
    keycloak:
      type: oauth2
      description: This API uses OAuth 2
      flows:
        clientCredentials:
          tokenUrl: {protocol}://{server}:{port}/auth/realms/{realm}/protocol/openid-connect/token
          variables:
            protocol:
              enum:
                - 'http'
                - 'https'
              default: 'http'
            server:
              default: 'keycloak.company.com'
            port:
              enum:
                - '80'
                - '443'
              default: '80'
            realm:
              default: 'myTenant'              
          scopes: {}
```

Currently, we use some workarounds to define such URL fragments (variables), it would be great to get rid of them in favor of standardization. Would it be possible to consider extending the OpenAPI Specification v4 in this direction?
