### DISCUSSION TITLE
Context property annotations

### DISCUSSION THREAD

**Discussion by darrelmiller** [OAI/sig-moonwalk#56] [Ideas]
JSON Schema is not aware of the context of usage of the schemas that it defines.  It has no notion that a schema is being used to create a resource, update it, or read it.

This leads people today to create multiple schemas so that there can be an accurate schema for each request or response content.  However, this introduces duplication or requires splitting the schema in order to reuse parts of the schema that don't change between responses.  This gets hard for documentation and code generators to process.

I am proposing that we introduce four new keywords that are boolean flags into the OAS JSON Schema vocabulary:

- computed - Generated by the server
- immutable - Can be provided on create but then read-only
- requiredForCreate - must be present when creating
- writeOnly - Can only be provided on create or update

Example:

```
   todo:
        type: "object"
        title: "Todo"
        properties:
            dateCreated: 
                type: string
                computed: true  
            owner:  
                type: string
                requiredForCreate: true 
                immutable: true
            title:   
                type: string
                requiredForCreate: true  
            secret:
                type: string
                writeOnly: true  
```

While this is a proposal aimed at Moonwalk, it would be possible to introduce these in OpenAPI 3.1.
