### DISCUSSION TITLE
Replace or remove discriminator

### DISCUSSION THREAD

**Discussion by MikeRalphson** [OAI/sig-moonwalk#57] [Ideas]
There are a number of issues with the current definition of `discriminator` (as well as a number of [open issues](https://github.com/OAI/OpenAPI-Specification/issues?q=is%3Aissue+is%3Aopen+label%3Adiscriminator)).

* It is not JSON Schema keyword-independent
* It claims to hint/short-circuit the evaluation of the `allOf`/`oneOf`/`anyOf` keywords
* It has an ill-defined short-hand notation for schema names, where the scoping rules are undefined
* It can only use schema names or `$ref`s not full sub-schemas
* Implementation ranges from patchy to non-existent

I think we can replace it with either JSON Schema `if`/`then`/`else` or a compact form such as:

```yaml
  switch:
    property: myType
    case:
      Cat:
        ... sub-schema
      Dog:
        ... sub-schema
      Lizard:
        ... sub-schema
```

**Comment by jdesrosiers** [comment]
There's a new keyword called [`propertyDependencies`](https://github.com/json-schema-org/json-schema-spec/issues/1082) that's likely to land in the next release of JSON Schema that is intended to cover `discriminator` use cases while fixing a lot of its problems. I'd suggest removing `discriminator` because `propertyDependencies` should make it not necessary anymore. If `propertyDependencies` isn't sufficient, I suggest we work it out in JSON Schema so all JSON Schema can benefit rather than just OpenAPI users.

**Comment by ahl** [comment]
Are there uses of the `discriminator` that **cannot** be modeled in JSON Schema (i.e. without the use of that field)? While it (maybe) affords the possibility of optimization, I haven't seen any implementations that are significantly more efficient than they would be using extant JSON Schema structures.

Further, I have found the description of `discriminator` confusing and complex. If the goal of this draft is simplicity, eliminating `discriminator` seems like a clear benefit with little to no down-side.

**Comment by sm-Fifteen** [comment]
There was also a proposed keyword by @handrews way back in https://github.com/OAI/OpenAPI-Specification/issues/2143#issuecomment-727068862 that merely used a JSON pointer to designate which field to use as the discriminating field, without requiring some kind of duplication of the validation functionnality.

```js
{
  "selectBy": "0/class",
  "oneOf": [
    {
      "if": {"properties": {"class": {"const": "foo"}}},
      "then": {...}
    },
    {
      "if": {"properties": {"class": {"const": "bar"}}},
      "then": {...}
    },
    ...
}
```

I do realize that it's very late to bring this up given `propertyDependencies` has already been merged into JSON Schema and it would be a lot more practical for everyone to not add too much stuff on top of JSON Schema (on top of the syntax being less cumbersome than `if-then`), but I still figured it was worth bringing up.

**Comment by mikekistler** [comment]
For the benefit of others reading this thread that aren't familiar with `propertyDependencies`, here's a link to the original proposal:

https://github.com/json-schema-org/json-schema-spec/issues/1082  (lots of discussion here)

and here is the PR that adds the keyword:

https://github.com/json-schema-org/json-schema-spec/pull/1143/files

**Comment by mikekistler** [comment]
I think `propertyDependencies` is a good addition to JSON Schema, but I guess I'm not quite ready to completely abandon `discriminator` in OpenAPI. But I agree that it should be simplified and some of its problems fixed. Here's an idea that came to me while reviewing https://github.com/OAI/OpenAPI-Specification/pull/3846 to clarify some details about `discriminator` in 3.1.x: ditch the "mapping" component and instead require each element of the `allOf` or `anyOf` to define its allowed values.

Here's an example:

```yaml
components:
  schemas:
    Pet:
      type: object
      discriminator: petType
      properties:
        name:
          type: string
      required:
      - name
      oneOf:
      - description: A representation of a cat
        type: object
        properties:
          petType:
            type: string
            const: "cat"
          huntingSkill:
            type: string
            description: The measured skill for hunting
            enum:
            - clueless
            - lazy
            - adventurous
            - aggressive
        required:
        - petType
        - huntingSkill
      - description: A representation of a dog
        type: object
        properties:
          petType:
            type: string
            const: "dog"
          packSize:
            type: integer
            format: int32
            description: the size of the pack the dog is from
            default: 0
            minimum: 0
        required:
        - petType
        - packSize
```

Note that each of the subschemas in the `oneOf` define the value(s) of `petType` that are allowed / map to that subschema.

The `discriminator` goes back to simply naming the property that will determine which variant to use. It is now purely a "hint" -- and normal JSON schema validators can simply ignore it since the schemas already contain the essential information.

I suppose this is not terribly different than `propertyDependencies`, but in my view it is simpler and only uses features of JSON schema that have been around for many versions / years, so should have good tooling support.
