### DISCUSSION TITLE
Consider shorthand for encoding method with path, eg; `post /foos/{id}`

### DISCUSSION THREAD

**Discussion by rattrayalex** [OAI/sig-moonwalk#61] [Ideas]
```yaml
paths:
  "post /speakers":
     requests: 
       createSpeaker:
         contentType: application/json
         …
```
as shorthand for
```yaml
paths:
  "speakers":
    requests:
      createSpeaker:
        method: post
        contentType: application/json
        …
```
Relates to this proposal to allow a `request` shorthand: https://github.com/OAI/moonwalk/discussions/60 and could perhaps be merged there, as it would make it much more common to be able to use a single `request` key, e.g.:

```yaml
paths:
  "post /speakers":
     request: 
       contentType: application/json
       …
```

Part of my motivation here is that it always felt strange to me that "retrieving" and "updating" a resource in an OpenAPI spec are nested in one place, but "creating" and "listing" the same resource are nested separately. Why nest at all? We're ultimately trying to get a flat list of operations. If we really do want to organize operations somehow, doing it based on [resources](https://github.com/OAI/moonwalk/discussions/30) might make a bit more sense.
