### DISCUSSION TITLE
Improve OAuth scope documentation

### DISCUSSION THREAD

**Discussion by garymazz** [OAI/sig-moonwalk#84] [Ideas]
The 3.1 documentation provides example of implementing scopes:
```
components:
  securitySchemes:
    oAuth2:
      type: oauth2
      description: For more information, see https://developers.getbase.com/docs/rest/articles/oauth2/requests
      flows: 
        implicit:
          authorizationUrl: https://api.getbase.com/oauth2/authorize
          scopes:
            read: Grant read-only access to all your data except for the account and user info
            write: Grant write-only access to all your data except for the account and user info
            profile: Grant read-only access to the account and user info only
        password: 
          tokenUrl: https://api.getbase.com/oauth2/token
          scopes: 
            read: Grant read-only access to all your data except for the account and user info
            write: Grant write-only access to all your data except for the account and user info
            profile: Grant read-only access to the account and user info only
```

Although it's a great example, some areas of the doc may be enhanced to clarify implementer guidance and user expectations: 

- Provide an example of scope content return to client that corresponds to scopes used in the example
- Provide an example implementing rbac groups
- Provide an example  implementing abac groups and attributes
- Clarify whether security can be applied to response schema and component schema elements
