### ISSUE TITLE
Change Tags to be a map instead of list

### ISSUE THREAD

**Issue by darrelmiller** [OAI/sig-moonwalk#52]
https://github.com/OAI/OpenAPI-Specification/discussions/2930#discussioncomment-4246927

**Comment by philsturgeon** [comment]
One of the main problems I have come across is different tools using Tags for completely different things.

1. Docs tools want to use them for navigation, so they should be human readable `Title Case`.
2. Code generators want to use them for namespacing or other codey stuff, so it should be camal, snake, or pascal case.
3. Third mutually exclusive thing no doubt.

Is there any point in coming up with some sort of other conept which can help to clarify the purpose of tags.

```
tags: 

  Foo: 
    description: Stuff
    purpose: navigation

  CodeStuff: 
    description: Stuff
    purpose: code
```

Those words are bad but I'm wondering if we can basically have multiple taxonomies which are more clear with their intent, whether thats defined by OAS or not. I'm not tied to any approach but I would like the hive mind to have a think about this use case if we're going to be making changes to tags.
